sudo: false
language: node_js
node_js:
  - "5.1"
  - "5"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
services:
- mongodb
env:
- NODE_ENV=production
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
install:
  - npm install -g istanbul
  - npm install
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage