sudo: required
language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
services:
  - mongodb
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g happiness
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g coveralls
  - npm install -g istanbul
  - npm install
before_script:
  - bower install
  - grunt
  - mongo --version
script:
  - istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
  - codecov